# QA to compare with MEM1

In [ ]:
import pandas as pd
from pprint import pprint
import matplotlib.pyplot as plt
import numpy as np


def get_df_from_train_gen(file: str):
    raw_jl = open(file, 'r', encoding='utf-8').read()

    import json, sys, pathlib

    json_list = []
    for i, raw_json in enumerate(raw_jl.strip().split("\n}")):
        if raw_json.strip():
            json_list.append(json.loads(raw_json + "\n}"))
    df = pd.DataFrame(json_list)
    return df

In [2]:
dfraw = get_df_from_train_gen("/nas/ucb/dayan/optimal-explorer-dev/verl-agent/checkpoints/verl_agent_alfworld/nqhotpotqa_grpo_qwen2.5-7b-instruct_16sfr_seed1_sc_False_belief_prompting_True/train_gen.txt")
dfraw.keys()
dfraw

,anchor_obs,index,data_source,uid,traj_uid,raw_prompt,is_action_valid,rewards,active_masks,response_ids_str,...,episode_lengths,episode_lengths_mean,episode_lengths_min,episode_lengths_max,success_rate,action_generation_failures_success_rate,belief_generation_failures_success_rate,successful_searches_success_rate,non_terminal_trajectories_success_rate,full_trajectory_strings
0,"[, , <hint>You have 1 turn left. You must answ...","[0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 6, 7, ...","[text, text, text, text, text, text, text, tex...","[0497c4ff-1b50-4e2a-9bf5-7abe0c43efa2, 0497c4f...","[ae72c98d-af78-4769-ad06-2ca55aa1059a, ae72c98...","[[{'role': 'user', 'content': 'Global Instruct...","[True, True, True, True, True, True, True, Tru...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[True, True, True, True, True, True, True, Tru...",[<think> The current belief holds that Basil W...,...,"[11, 11, 11, 5, 5, 12, 12, 12, 12, 12, 7, 5, 5...","[7.96875, 7.96875, 7.96875, 7.96875, 7.96875, ...","[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, ...","[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 1...","[0.5625, 0.5625, 0.5625, 0.5625, 0.5625, 0.562...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.625, 3.625, 3.625, 3.625, 3.625, 3.625, 3.6...","[0.28125, 0.28125, 0.28125, 0.28125, 0.28125, ...",[system\nYou will answer multiple complex ques...
1,"[, <hint>You have 5 turns left.</hint>\n\nDoc ...","[1, 2, 2, 2, 2, 3, 3, 4, 5, 6, 6, 7, 7, 7, 8, ...","[text, text, text, text, text, text, text, tex...","[d484ac81-e9b5-4d96-9a5e-dd16b74f2ab5, 7adf498...","[a687e350-7e97-416f-996a-c0d7a918b9e0, 9f09683...","[[{'role': 'user', 'content': 'Global Instruct...","[True, True, True, True, True, True, True, Tru...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[True, True, True, True, True, True, True, Tru...","[<think> Based on the current belief, the prod...",...,"[12, 12, 12, 12, 12, 12, 12, 5, 5, 11, 11, 9, ...","[7.21875, 7.21875, 7.21875, 7.21875, 7.21875, ...","[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...","[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 1...","[0.5625, 0.5625, 0.5625, 0.5625, 0.5625, 0.562...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[3.1875, 3.1875, 3.1875, 3.1875, 3.1875, 3.187...","[0.15625, 0.15625, 0.15625, 0.15625, 0.15625, ...",[system\nYou will answer multiple complex ques...

In [3]:
pd.DataFrame(dfraw.iloc[0].to_dict())

,anchor_obs,index,data_source,uid,traj_uid,raw_prompt,is_action_valid,rewards,active_masks,response_ids_str,...,episode_lengths,episode_lengths_mean,episode_lengths_min,episode_lengths_max,success_rate,action_generation_failures_success_rate,belief_generation_failures_success_rate,successful_searches_success_rate,non_terminal_trajectories_success_rate,full_trajectory_strings
0,,0,text,0497c4ff-1b50-4e2a-9bf5-7abe0c43efa2,ae72c98d-af78-4769-ad06-2ca55aa1059a,"[{'role': 'user', 'content': 'Global Instructi...",True,0,True,<think> The current belief holds that Basil Wr...,...,11,7.96875,5,12,0.5625,0.0,0.0,3.625,0.28125,system\nYou will answer multiple complex quest...
1,,0,text,0497c4ff-1b50-4e2a-9bf5-7abe0c43efa2,ae72c98d-af78-4769-ad06-2ca55aa1059a,"[{'role': 'user', 'content': 'Global Instructi...",True,0,True,"<think> The producer of ""The Harvest Shall Com...",...,11,7.96875,5,12,0.5625,0.0,0.0,3.625,0.28125,system\nYou will answer multiple complex quest...
2,<hint>You have 1 turn left. You must answer th...,0,text,0497c4ff-1b50-4e2a-9bf5-7abe0c43efa2,ae72c98d-af78-4769-ad06-2ca55aa1059a,"[{'role': 'user', 'content': 'Global Instructi...",True,0,True,"<think>Based on the environment feedback, ther...",...,11,7.96875,5,12,0.5625,0.0,0.0,3.625,0.28125,system\nYou will answer multiple complex quest...
3,Who was the producer of The Harvest Shall Come...,1,text,0497c4ff-1b50-4e2a-9bf5-7abe0c43efa2,2d0a30a3-acd5-4a39-ab86-4abf38db0282,"[{'role': 'system', 'content': 'You will answe...",True,0,True,<think> ... </think><search> producer of The H...,...,5,7.96875,5,12,0.5625,0.0,0.0,3.625,0.28125,system\nYou will answer multiple complex quest...
4,<hint>You have 5 turns left.</hint>\n\nDoc 1(T...,1,text,0497c4ff-1b50-4e2a-9bf5-7abe0c43efa2,2d0a30a3-acd5-4a39-ab86-4abf38db0282,"[{'role': 'user', 'content': 'Global Instructi...",True,0,True,"<think>From the search results, I have identif...",...,5,7.96875,5,12,0.5625,0.0,0.0,3.625,0.28125,system\nYou will answer multiple complex quest...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,,29,text,60ec209b-39ff-4d45-a29f-9a9d3b06c6ec,85cc28cb-beb9-4d79-83f3-8c0b7f38a745,"[{'role': 'user', 'content': 'Global Instructi...",True,0,True,<think> The current belief states that Lukas M...,...,5,7.96875,5,12,0.5625,0.0,0.0,3.625,0.28125,system\nYou will answer multiple complex quest...
252,,30,text,a5254aec-c1ef-41ca-8479-73f5829e7364,6233e25a-e3d8-4fd4-8834-1646c164d614,"[{'role': 'user', 'content': 'Global Instructi...",True,2,True,<think> The current belief states that 'London...,...,5,7.96875,5,12,0.5625,0.0,0.0,3.625,0.28125,system\nYou will answer multiple complex quest...
253,,31,text,a5254aec-c1ef-41ca-8479-73f5829e7364,b1c4a8e5-24bf-41f1-8cae-ec9244a660c3,"[{'role': 'user', 'content': 'Global Instructi...",True,0,True,<think> The current belief states that 'London...,...,5,7.96875,5,12,0.5625,0.0,0.0,3.625,0.28125,system\nYou will answer multiple complex quest...
254,<hint>You have 4 turns left.</hint>\n\nDoc 1(T...,31,text,a5254aec-c1ef-41ca-8479-73f5829e7364,b1c4a8e5-24bf-41f1-8cae-ec9244a660c3,"[{'role': 'user', 'content': 'Global Instructi...",True,0,True,"<think>Based on the documents, 'London Is the ...",...,5,7.96875,5,12,0.5625,0.0,0.0,3.625,0.28125,system\nYou will answer multiple complex quest...
255,,22,text,0c143829-7234-458b-87bd-784a179fd925,7b6d31f4-db40-4521-b975-bfda8edaf0e6,"[{'role': 'user', 'content': 'Global Instructi...",True,0,True,<think> The current belief states that the ing...,...,12,7.96875,5,12,0.5625,0.0,0.0,3.625,0.28125,system\nYou will answer multiple complex quest...